"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import MapView,{Place} from "./MapView";
import {categories,checklistByDuration,guideItems,GuideItem} from "./data";
type Page="home"|"guide"|"ask"|"nearby"|"my";
type Profile={nickname:string;birthYear:number;region:string;duration:string;language:string};
const nav:[Page,string,string][]=[["home","홈","⌂"],["guide","생활가이드","▤"],["ask","AI에게 질문","?"],["nearby","내 주변","⌖"],["my","마이 라이프","♙"]];
const path:Record<Page,string>={home:"/home",guide:"/guide",ask:"/ask",nearby:"/nearby",my:"/my"};
const samplePlaces:Place[]=[
 {id:"support",name:"인천 외국인주민지원센터 (샘플)",category:"외국인 지원",latitude:37.4642,longitude:126.6758,distance_km:1.2,hours:"월–금 09:00–18:00",description:"생활 전반 상담, 통역 지원, 타 기관 연계를 제공해요.",languages:["KO","EN","VI","ZH"],audience:"모든 외국인 주민",sample:true},
 {id:"labor",name:"남동 노동상담소 (샘플)",category:"노동 상담",latitude:37.4477,longitude:126.7312,distance_km:2.4,hours:"월–금 10:00–20:00",description:"임금체불, 계약, 산재 절차를 도와줘요.",languages:["KO","EN","VI"],audience:"외국인 노동자",sample:true},
 {id:"clinic",name:"송도 지역 보건진료소 (샘플)",category:"의료",latitude:37.3892,longitude:126.6473,distance_km:.9,hours:"월–금 09:00–17:00",description:"기본 건강검진과 예방접종 안내를 받을 수 있어요.",languages:["KO","EN"],audience:"외국인 주민 포함 지역주민",sample:true},
 {id:"admin",name:"행정복지센터 민원창구 (샘플)",category:"행정 서비스",latitude:37.5451,longitude:126.6761,distance_km:.6,hours:"월–금 09:00–18:00",description:"전입신고, 증명서 발급, 생활 민원을 도와줘요.",languages:["KO","EN"],audience:"모든 주민",sample:true},
 {id:"bus",name:"시외버스터미널 안내창구 (샘플)",category:"교통",latitude:37.4421,longitude:126.7011,distance_km:3.1,hours:"매일 06:00–22:00",description:"승차권 구매와 노선·시간표 안내를 받을 수 있어요.",languages:["KO","EN"],audience:"모든 여행자",sample:true}
];
function useStored<T>(key:string,initial:T){const [v,setV]=useState(initial);useEffect(()=>{const raw=localStorage.getItem(key);if(raw)try{setV(JSON.parse(raw))}catch{}},[key]);const save=(n:T)=>{setV(n);localStorage.setItem(key,JSON.stringify(n))};return [v,save] as const}
function Header({title,sub}:{title:string;sub?:string}){return <header className="page-header"><h1>{title}</h1>{sub&&<p>{sub}</p>}</header>}
function GuideCard({item,onOpen}:{item:GuideItem;onOpen:(i:GuideItem)=>void}){return <button className="guide-card" onClick={()=>onOpen(item)}><span className="guide-icon">{item.icon}</span><span><b>{item.title}</b><small>{item.desc}</small><em>{item.badge}</em></span><i>›</i></button>}
export default function MainApp({page}:{page:Page}){
 const [profile]=useStored<Profile>("injoy-profile",{nickname:"유학생",birthYear:2001,region:"연수구",duration:"1개월 미만",language:"한국어"});
 const [saved,setSaved]=useStored<string[]>("injoy-saved",[]),[done,setDone]=useStored<string[]>("injoy-checklist",[]),[messages,setMessages]=useStored<{role:"user"|"assistant";content:string}[]>("injoy-messages",[]);
 const [detail,setDetail]=useState<GuideItem|null>(null),[filter,setFilter]=useState("전체"),[placeFilter,setPlaceFilter]=useState("전체"),[draft,setDraft]=useState("");
 const visibleGuides=filter==="전체"?guideItems:guideItems.filter(i=>i.category===filter);const places=placeFilter==="전체"?samplePlaces:samplePlaces.filter(p=>p.category===placeFilter);
 const checklist=checklistByDuration[profile.duration]||checklistByDuration["1개월 미만"];
 function openGuide(i:GuideItem){setDetail(i)}function toggleSaved(id:string){setSaved(saved.includes(id)?saved.filter(x=>x!==id):[...saved,id])}function toggleDone(id:string){setDone(done.includes(id)?done.filter(x=>x!==id):[...done,id])}
 async function ask(e:FormEvent){e.preventDefault();const q=draft.trim();if(!q)return;const next=[...messages,{role:"user" as const,content:q}];setMessages(next);setDraft("");try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,profile})});const data=await res.json();setMessages([...next,{role:"assistant",content:data.answer||"답변을 준비하지 못했어요."}])}catch{setMessages([...next,{role:"assistant",content:"연결이 원활하지 않아요. 생활가이드에서 관련 정보를 먼저 확인해주세요."}])}}
 return <main className="app-shell"><section className="app-content">
  {page==="home"&&<><section className="hero"><span>INJOY · LIFE NAVIGATOR</span><h1>{profile.nickname}님,<br/>인천 생활을 함께할게요</h1><p>{profile.region} · 체류기간 {profile.duration}</p><div>오늘 필요한 정보만 쉽고 빠르게 확인하세요.</div></section><section className="content-section"><h2>생활가이드</h2><div className="category-grid">{[["🚌","교통"],["🏥","의료"],["💳","은행·금융"],["🏠","주거"],["📱","통신"],["♻️","일상생활"],["💼","직장·노동"],["🏛️","행정·비자"],["🚨","긴급상황"]].map(x=><Link href={`/guide?category=${encodeURIComponent(x[1])}`} key={x[1]}><span>{x[0]}</span>{x[1]}</Link>)}</div></section><section className="content-section"><h2>당신을 위한 추천</h2>{guideItems.slice(0,3).map(i=><GuideCard key={i.id} item={i} onOpen={openGuide}/>)}</section></>}
  {page==="guide"&&<><Header title="생활가이드" sub="긴 문서가 아니라, 실행 가능한 단계로 정리했어요."/><div className="chip-row">{categories.map(c=><button className={filter===c?"active":""} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div>{visibleGuides.map(i=><GuideCard key={i.id} item={i} onOpen={openGuide}/>)}</>}
  {page==="ask"&&<><Header title="AI에게 질문" sub="한국 생활에서 막히는 걸 편하게 물어보세요."/>{messages.length===0&&<section className="chat-hero"><b>✦ LIFE NAVIGATOR</b><h2>{profile.nickname}님, 무엇이 궁금하세요?</h2><p>행정·의료·은행·통신처럼 처음엔 놓치기 쉬운 정보도 함께 안내해요.</p></section>}<div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.role==="assistant"&&<b>✦ AI 답변</b>}<p>{m.content}</p></div>)}</div><div className="suggestions">{["외국인등록증은 언제 신청해야 하나요?","은행 계좌를 만들려면 무엇이 필요한가요?","병원 통역은 어디서 도움받나요?"].map(q=><button key={q} onClick={()=>setDraft(q)}>{q}</button>)}</div><form className="chat-form" onSubmit={ask}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="무엇이든 물어보세요..."/><button>↑</button></form></>}
  {page==="nearby"&&<><Header title="내 주변" sub="실제로 도움을 받을 수 있는 곳들."/><MapView places={places}/><div className="chip-row">{["전체","외국인 지원","노동 상담","의료","행정 서비스","교통"].map(c=><button className={placeFilter===c?"active":""} onClick={()=>setPlaceFilter(c)} key={c}>{c}</button>)}</div>{places.map(p=><article className="place-card" key={p.id}><div><h3>{p.name}</h3>{p.sample&&<em>샘플 데이터</em>}</div><small>{p.distance_km} km · {p.category} · {p.hours}</small><p>{p.description}</p><div className="tags">{p.languages.map(l=><span key={l}>{l}</span>)}<b>{p.audience}</b></div><div className="place-actions"><Link href="/ask">AI에게 질문</Link><a className="primary" href={`https://map.naver.com/p/search/${encodeURIComponent(p.name)}`} target="_blank">⌁ 길찾기</a></div></article>)}</>}
  {page==="my"&&<><div className="my-head"><Header title="마이 라이프"/><span>KO</span></div><section className="profile-card"><div><b>{profile.region} · 체류기간 {profile.duration}</b><small>{done.length}/{checklist.length} 완료 · {saved.length}개 저장</small></div><Link href="/">프로필 수정</Link></section><section className="content-section"><h2>나의 체크리스트</h2><p className="section-sub">한국 생활 시작하기</p>{checklist.map(([id,title])=><div className="check-row" key={id}><button onClick={()=>toggleDone(id)} className={done.includes(id)?"done":""}>{done.includes(id)?"✓":""}</button><b className={done.includes(id)?"strike":""}>{title}</b><Link href="/guide">자세히 보기</Link></div>)}</section><section className="content-section"><h2>저장한 정보</h2>{saved.length===0?<p className="empty">아직 저장한 정보가 없어요.</p>:guideItems.filter(i=>saved.includes(i.id)).map(i=><GuideCard key={i.id} item={i} onOpen={openGuide}/>)}</section><section className="content-section"><h2>아직 모를 수 있는 것들</h2><p className="section-sub">질문·체크리스트 기록을 바탕으로 골랐어요.</p>{guideItems.filter(i=>!saved.includes(i.id)).slice(0,3).map(i=><GuideCard key={i.id} item={i} onOpen={openGuide}/>)}</section></>}
  {detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><article className="detail-sheet" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}>×</button><span className="detail-icon">{detail.icon}</span><em>{detail.badge}</em><h2>{detail.title}</h2><p>{detail.desc}</p><section><b>왜 중요한가요</b><p>한국 생활에서 미리 알아두면 시간과 시행착오를 줄일 수 있는 정보예요.</p></section><button className="save-button" onClick={()=>toggleSaved(detail.id)}>{saved.includes(detail.id)?"✓ 저장됨":"＋ 저장하기"}</button></article></div>}
 </section><nav className="bottom-nav">{nav.map(([id,label,icon])=><Link key={id} className={page===id?"active":""} href={path[id]}><span>{icon}</span>{label}</Link>)}</nav></main>
}
