"use client";
import { FormEvent,useEffect,useState } from "react";
import Link from "next/link";
import MapView,{Place} from "./MapView";
import {categories,checklistByDuration,guideItems,GuideItem} from "./data";
import nearbyPlaces from "../public/nearby_places.json";
import appTranslations from "./app-translations.json";
import {languages,LocaleCode} from "./onboarding-i18n";
type Page="home"|"guide"|"ask"|"nearby"|"my";
type Profile={nickname:string;birthYear:number;region:string;duration:string;language:string;hasArc?:boolean;hasAccount?:boolean;purpose?:string};
type ContactRecommendation={institution:string;department:string;team:string;phone:string;address:string;district:string;type:string};
type ChatAction={label:string;href?:string;checkId?:string;guideId?:string;contact?:ContactRecommendation;places?:Place[]};
type ChatMessage={role:"user"|"assistant";content:string;contact?:ContactRecommendation|null;source?:string;actions?:ChatAction[]};
const nav:[Page,string,string][]=[["home","홈","⌂"],["guide","생활가이드","▤"],["ask","AI에게 질문","?"],["nearby","내 주변","⌖"],["my","마이 라이프","♙"]];
const path:Record<Page,string>={home:"/home",guide:"/guide",ask:"/ask",nearby:"/nearby",my:"/my"};
const allPlaces=nearbyPlaces as Place[];
const placeCategories=["전체","행정·복지",...Array.from(new Set(allPlaces.map(place=>place.category))).filter(category=>category!=="행정·복지")];
function useStored<T>(key:string,initial:T){const [v,setV]=useState(initial);useEffect(()=>{const raw=localStorage.getItem(key);if(raw)try{setV(JSON.parse(raw))}catch{}},[key]);const save=(n:T)=>{setV(n);localStorage.setItem(key,JSON.stringify(n))};return [v,save] as const}
function Header({title,sub}:{title:string;sub?:string}){return <header className="page-header"><h1>{title}</h1>{sub&&<p>{sub}</p>}</header>}
function GuideCard({item,onOpen,tr,reason}:{item:GuideItem;onOpen:(i:GuideItem)=>void;tr:(text:string)=>string;reason?:string}){return <button className="guide-card" onClick={()=>onOpen(item)}><span className="guide-icon">{item.icon}</span><span><b>{tr(item.title)}</b><small>{tr(item.desc)}</small><span className="guide-badges"><em>{tr(item.badge)}</em>{reason&&<mark>✦ {tr(reason)}</mark>}</span></span><i>›</i></button>}
export default function MainApp({page}:{page:Page}){
 const [profile]=useStored<Profile>("injoy-profile",{nickname:"유학생",birthYear:2001,region:"연수구",duration:"1개월 미만",language:"한국어"});
 const [saved,setSaved]=useStored<string[]>("injoy-saved",[]),[done,setDone]=useStored<string[]>("injoy-checklist",[]),[extraChecklist,setExtraChecklist]=useStored<[string,string][]>("injoy-extra-checklist",[]),[messages,setMessages]=useStored<ChatMessage[]>("injoy-messages",[]),[targetContact,setTargetContact]=useStored<ContactRecommendation|null>("injoy-target-contact",null),[targetPlaces,setTargetPlaces]=useStored<Place[]>("injoy-target-places",[]);
 const [filter,setFilter]=useState("전체"),[placeFilter,setPlaceFilter]=useState("전체"),[draft,setDraft]=useState(""),[locale,setLocale]=useState<LocaleCode>("ko");
 useEffect(()=>{const legacy:Record<string,LocaleCode>={"한국어":"ko","English":"en"};const raw=localStorage.getItem("injoy-language")||profile.language||"ko";const next=(legacy[raw]||raw) as LocaleCode;if(languages.some(item=>item.code===next)){setLocale(next);document.documentElement.lang=next}},[profile.language]);
 useEffect(()=>{if(page!=="nearby")return;const category=new URLSearchParams(location.search).get("category");if(category&&placeCategories.includes(category))setPlaceFilter(category)},[page]);
 const dictionary=appTranslations[locale] as Record<string,string>;const tr=(text:string)=>dictionary?.[text]||text;
 const visibleGuides=filter==="전체"?[...guideItems].sort((a,b)=>Number(b.category==="행정·비자")-Number(a.category==="행정·비자")):guideItems.filter(i=>i.category===filter);const places=(placeFilter==="전체"?allPlaces:allPlaces.filter(p=>p.category===placeFilter)).sort((a,b)=>{const score=(p:Place)=>(p.district===profile.region?10:0)+(p.category==="행정·복지"?5:0)+(/구청|행정복지센터|주민센터/.test(p.name)?2:0);return score(b)-score(a)});const displayPlaces=places.map(p=>({...p,category:tr(p.category),hours:tr(p.hours),description:tr(p.description),district:tr(p.district)}));const nearbyDisplayPlaces=targetPlaces.length?targetPlaces:displayPlaces;
 const baseChecklist=checklistByDuration[profile.duration]||checklistByDuration["1개월 미만"];
 const priorityIds=[...(!profile.hasArc?["support"]:[]),...(!profile.hasAccount?["bank","banking"]:[]),...(profile.purpose==="노동자"?["contract","emergency"]:[]),...(profile.purpose==="유학생"?["phone","bank","korean"]:[])];
 const actionChecklist:Record<string,string>={support:"가까운 지원기관 찾아보기",contract:"근로계약서 확인하기",hospital:"병원 이용법 알기",bank:"은행 기본 이해하기",waste:"쓰레기 분리배출 이해하기",phone:"휴대폰 개통하기",transport:"대중교통 이용법 익히기","bus-booking":"시외·고속버스 예매 방법 확인하기",visa:"외국인등록 및 체류기간 확인하기",address:"주소 변경 신고 확인하기",insurance:"건강보험 확인하기",lease:"임대차 계약 확인하기",emergency:"긴급 연락처 저장하기"};
 const checklist=[...baseChecklist,...extraChecklist.filter(item=>!baseChecklist.some(base=>base[0]===item[0]))].sort((a,b)=>Number(priorityIds.includes(b[0]))-Number(priorityIds.includes(a[0])));
 const latestQuestion=[...messages].reverse().find(message=>message.role==="user")?.content||"";
 const guideReason=(item:GuideItem)=>{if(!profile.hasArc&&item.id==="visa")return "외국인등록증 미보유";if(!profile.hasAccount&&item.id==="bank")return "은행 계좌 미보유";if(profile.purpose==="노동자"&&item.id==="labor")return "근로자 프로필";if(profile.purpose==="유학생"&&["phone","bank"].includes(item.id))return "유학생에게 중요";if(latestQuestion&&[item.title,item.category].some(value=>latestQuestion.includes(value.slice(0,2))))return "최근 질문과 관련";if(!saved.includes(item.id))return `${profile.duration} 맞춤`;return "저장한 관심 정보"};
 // 체크리스트 항목 id가 생활가이드 id와 항상 같지는 않아서(예: "hospital" ↔ "clinic"),
 // id가 정확히 일치하는 가이드가 없으면 같은 카테고리의 가이드로 대신 연결한다.
 const guideForCheck=(id:string,category?:string)=>guideItems.find(g=>g.id===id)||(category?guideItems.find(g=>g.category===category):undefined);
 const rankedGuides=[...guideItems].sort((a,b)=>{const score=(item:GuideItem)=>(!profile.hasArc&&item.id==="visa"?8:0)+(!profile.hasAccount&&item.id==="bank"?7:0)+(profile.purpose==="노동자"&&item.id==="labor"?6:0)+(profile.purpose==="유학생"&&["phone","bank"].includes(item.id)?5:0)+(saved.includes(item.id)?-2:1);return score(b)-score(a)});
 const briefItems=checklist.filter(item=>!done.includes(item[0])).slice(0,2);
 const benefitReasons=[profile.region,profile.purpose||"생활 적응",profile.duration];
 function openGuide(i:GuideItem){location.href=`/guide/${i.id}`}function toggleDone(id:string){if(page==="home"){const item=checklist.find(entry=>entry[0]===id);const guide=guideForCheck(id,item?.[2]);location.href=guide?`/guide/${guide.id}`:"/my";return}setDone(done.includes(id)?done.filter(x=>x!==id):[...done,id])}
 function runAction(action:ChatAction){if(action.checkId){if(!checklist.some(item=>item[0]===action.checkId))setExtraChecklist([...extraChecklist,[action.checkId,actionChecklist[action.checkId]||"확인할 정보"]]);localStorage.setItem("injoy-focus-check",action.checkId)}if(action.guideId&&!saved.includes(action.guideId))setSaved([...saved,action.guideId]);if(action.contact)setTargetContact(action.contact);else if(action.places?.length)setTargetContact(null);if(action.places)setTargetPlaces(action.places);const destination=action.href||(action.guideId?`/guide/${action.guideId}`:action.checkId?"/my":undefined);if(destination)location.href=destination}
 // 실제로 주제가 매칭됐거나(기관 후보를 받았거나) 카테고리 키워드가 잡혔을 때만 "다음 행동" 버튼을 붙인다.
 // 매칭이 하나도 없으면(=잡담/인사 등 실질 정보가 없는 응답) 빈 배열을 반환해 엉뚱한 체크리스트/가이드 버튼이 안 붙게 한다.
 function actionsFor(q:string,contact?:ContactRecommendation|null):ChatAction[]{const lower=q.toLowerCase();let guideId="visa",checkId="support",matched=false;if(/시외|고속버스|터미널|버스타고|예매/.test(lower)){guideId="bus-booking";checkId="bus-booking";matched=true}else if(/교통카드|티머니|캐시비|버스|지하철|대중교통|환승/.test(lower)){guideId="transit-card";checkId="transport";matched=true}else if(/임금|노동|근로|해고|산재/.test(lower)){guideId="labor";checkId="contract";matched=true}else if(/건강보험|보험료/.test(lower)){guideId="insurance";checkId="insurance";matched=true}else if(/병원|의료|아파|진료|내과|치과/.test(lower)){guideId="clinic";checkId="hospital";matched=true}else if(/은행|계좌|카드|뱅킹|송금/.test(lower)){guideId="bank";checkId="bank";matched=true}else if(/쓰레기|재활용|분리배출|종량제/.test(lower)){guideId="waste";checkId="waste";matched=true}else if(/휴대폰|핸드폰|통신|유심|알뜰폰/.test(lower)){guideId="phone";checkId="phone";matched=true}else if(/주소|전입|체류지/.test(lower)){guideId="address";checkId="address";matched=true}else if(/월세|전세|임대차|집 계약|등기부/.test(lower)){guideId="lease";checkId="lease";matched=true}else if(/비자|외국인등록|체류기간|출입국/.test(lower)){guideId="visa";checkId="visa";matched=true}else if(/응급|긴급|119|112/.test(lower)){guideId="emergency";checkId="emergency";matched=true}if(!matched&&!contact)return [];let mapTargets:Place[]=[];if(guideId==="bus-booking"){mapTargets=[{id:"place-2",name:"인천종합터미널 (버스)",category:"교통",latitude:37.4392951,longitude:126.7024478,address:"인천 미추홀구 연남로 35",district:"미추홀구",phone:"1666-7114",hours:"노선별 운행시간 확인",description:"시외·고속버스 승차와 예매 정보를 확인할 수 있는 인천 버스터미널이에요.",website:"",source:"지도 기관 데이터"}]}else if(guideId==="waste"){const localCenter=allPlaces.find(place=>place.district===profile.region&&/행정복지센터|주민센터|구청/.test(place.name));if(localCenter)mapTargets=[localCenter];else{const centers:Record<string,[number,number]>={연수구:[37.4102,126.6783],남동구:[37.4472,126.7315],미추홀구:[37.4636,126.6504],서구:[37.5455,126.6760],서해구:[37.5455,126.6760],검단구:[37.5947,126.6983],중구:[37.4738,126.6217],제물포구:[37.4738,126.6217],영종도구:[37.4925,126.4880]};const [latitude,longitude]=centers[profile.region]||[37.4563,126.7052];mapTargets=[{id:"ai-waste-office",name:contact?.institution||`${profile.region} 행정기관`,category:"행정·복지",latitude,longitude,address:contact?.address||`${profile.region} 관할`,district:profile.region,phone:contact?.phone||"",hours:"방문 전 전화 확인",description:`쓰레기·분리배출 문의: ${contact?.department||"청소·자원순환 담당 부서"}`,website:"",source:"AI 추천"}]}}return [{label:"체크리스트에 추가",checkId,href:"/my"},{label:"관련 가이드 저장",guideId,href:`/guide/${guideId}`},...((contact||mapTargets.length)?[{label:"가까운 기관 확인",contact:contact||undefined,places:mapTargets,href:"/nearby"}]:[])]}
 async function ask(e:FormEvent){e.preventDefault();const q=draft.trim();if(!q)return;const history=messages.slice(-10).map(m=>({role:m.role,content:m.content}));const next:ChatMessage[]=[...messages,{role:"user",content:q}];setMessages(next);setDraft("");try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,history,profile:{...profile,locale,language:languages.find(item=>item.code===locale)?.name||locale}})});const data=await res.json();const actions=data.source==="기본 대화"?undefined:actionsFor(q,data.contact);setMessages([...next,{role:"assistant",content:data.answer||tr("답변을 준비하지 못했어요."),contact:data.contact,source:data.source,actions}])}catch{setMessages([...next,{role:"assistant",content:tr("연결이 원활하지 않아요. 생활가이드에서 관련 정보를 먼저 확인해주세요."),actions:actionsFor(q)}])}}
 return <main className="app-shell"><div className="app-speaker"/><header className="app-topbar"><span className="app-brand"><i>INJOY</i><b>INCHEON</b></span><span className="locale-pill">{languages.find(item=>item.code===locale)?.flag} {locale.toUpperCase()}</span></header><section className="app-content">
  {page==="home"&&<><section className="hero"><span>INJOY · LIFE NAVIGATOR</span><h1>{profile.nickname},<br/>{tr("인천 생활을 함께할게요")}</h1><p>{tr(profile.region)} · {tr("체류기간")} {tr(profile.duration)}</p></section><section className="personal-brief"><header><div><small>✦ PERSONAL BRIEFING</small><h2>{tr("오늘의 맞춤 브리핑")}</h2></div><span>{briefItems.length}{tr("개 추천")}</span></header><p>{tr(profile.region)} · {tr(profile.purpose||"생활 적응")} · {tr(profile.duration)} {tr("프로필을 반영했어요.")}</p><div>{briefItems.map(([id,title])=><button key={id} onClick={()=>toggleDone(id)}><span><b>{tr(title)}</b><small>{tr(priorityIds.includes(id)?"프로필 조건에 따라 우선 추천":"아직 완료하지 않은 항목")}</small></span><em>›</em></button>)}</div><Link href="/my">{tr("전체 맞춤 체크리스트 보기")} →</Link></section><section className="incheon-benefits"><header><small>✦ {tr("인천에서 받을 수 있어요")}</small><span>{tr("맞춤 혜택")}</span></header><article><div><h2>{tr(`${profile.region}에서 생활하거나 근무하시나요?`)}</h2><p>{tr("가까운 외국인 주민 지원기관에서 생활·노동·통역 상담을 받을 수 있어요.")}</p></div><Link href="/nearby?category=직장·노동">{tr("확인해보기")} →</Link></article><article><div><h2>{tr("매일 대중교통으로 출퇴근하시나요?")}</h2><p>{tr("인천 I-패스 지원 대상과 대중교통 환급 조건을 확인해보세요.")}</p></div><Link href="/guide/transit-card">{tr("확인해보기")} →</Link></article><footer><b>{tr("추천 이유")}</b>{benefitReasons.map(reason=><span key={reason}>{tr(reason)}</span>)}</footer></section><section className="content-section"><h2>{tr("생활가이드")}</h2><div className="category-grid">{[["🚌","교통"],["🏥","의료"],["💳","은행·금융"],["🏠","주거"],["📱","통신"],["♻️","일상생활"],["💼","직장·노동"],["🏛️","행정·비자"],["🚨","긴급상황"]].map(x=><Link href={`/guide?category=${encodeURIComponent(x[1])}`} key={x[1]}><span>{x[0]}</span>{tr(x[1])}</Link>)}</div></section><section className="content-section"><h2>{tr("당신을 위한 추천")}</h2><p className="section-sub">{tr("프로필과 완료 기록을 바탕으로 골랐어요.")}</p>{rankedGuides.slice(0,3).map(i=><GuideCard key={i.id} item={i} onOpen={openGuide} tr={tr} reason={guideReason(i)}/>)}</section></>}
  {page==="guide"&&<><Header title={tr("생활가이드")} sub={tr("긴 문서가 아니라, 실행 가능한 단계로 정리했어요.")}/><div className="chip-row">{categories.map(c=><button className={filter===c?"active":""} onClick={()=>setFilter(c)} key={c}>{tr(c)}</button>)}</div>{visibleGuides.map(i=><GuideCard key={i.id} item={i} onOpen={openGuide} tr={tr}/>)}</>}
  {page==="ask"&&<><Header title={tr("AI에게 질문")} sub={tr("한국 생활에서 막히는 걸 편하게 물어보세요.")}/>{messages.length===0&&<section className="chat-hero"><b>✦ LIFE NAVIGATOR</b><h2>{profile.nickname}, {tr("무엇이 궁금하세요?")}</h2><p>{tr("행정·의료·은행·통신처럼 처음엔 놓치기 쉬운 정보도 함께 안내해요.")}</p></section>}<div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.role==="assistant"&&<b>✦ {tr("AI 답변")}</b>}<p>{m.content}</p>{m.contact&&<section className="contact-card"><small>{tr(m.contact.district)} · {tr("기준 추천 기관")}</small><strong>{m.contact.institution}</strong><span>{m.contact.department}{m.contact.team&&` · ${m.contact.team}`}</span>{m.contact.address&&<address>{m.contact.address}</address>}<div><a href={`tel:${m.contact.phone.replace(/\s/g,"")}`}>☎ {m.contact.phone}</a><a href={`https://map.naver.com/p/search/${encodeURIComponent(m.contact.address||m.contact.institution)}`} target="_blank" rel="noreferrer">{tr("지도에서 보기")} →</a></div></section>}{!!m.actions?.length&&<div className="next-actions"><small>{tr("다음 행동을 바로 실행해보세요")}</small>{m.actions.map(action=><button key={action.label} onClick={()=>runAction(action)}>＋ {tr(action.label)}</button>)}</div>}</div>)}</div><div className="suggestions">{["외국인등록증은 언제 신청해야 하나요?","쓰레기 배출은 어디에 문의하나요?","가까운 내과 전화번호를 알려주세요"].map(q=><button key={q} onClick={()=>setDraft(q)}>{tr(q)}</button>)}</div><form className="chat-form" onSubmit={ask}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder={tr("무엇이든 물어보세요...")}/><button>↑</button></form></>}
  {page==="nearby"&&<><Header title={tr("내 주변")} sub={tr("실제로 도움을 받을 수 있는 곳들.")}/>{targetPlaces.length>0&&<div className="map-target-banner"><b>✦ {tr("질문과 관련된 장소만 표시 중")}</b><button onClick={()=>{setTargetContact(null);setTargetPlaces([])}}>{tr("전체 보기")}</button></div>}{targetContact&&<article className="target-place"><header><span>✦ {tr("AI가 찾은 관련 기관")}</span><button onClick={()=>{setTargetContact(null);setTargetPlaces([])}}>×</button></header><small>{tr(targetContact.district)} · {tr("질문과 관련된 담당 부서")}</small><h2>{targetContact.institution}</h2><p>{targetContact.department}{targetContact.team&&` · ${targetContact.team}`}</p>{targetContact.address&&<address>⌖ {targetContact.address}</address>}<div><a href={`tel:${targetContact.phone.replace(/\s/g,"")}`}>☎ {targetContact.phone}</a><a href={`https://map.naver.com/p/search/${encodeURIComponent([targetContact.institution,targetContact.department,targetContact.address].filter(Boolean).join(" "))}`} target="_blank" rel="noreferrer">{tr("지도에서 정확히 보기")} →</a></div></article>}<MapView places={nearbyDisplayPlaces}/>{targetPlaces.length===0&&<div className="chip-row">{placeCategories.map(c=><button className={placeFilter===c?"active":""} onClick={()=>setPlaceFilter(c)} key={c}>{tr(c)}</button>)}</div>}{nearbyDisplayPlaces.map(p=><article className="place-card" key={p.id}><div><h3>{p.name}</h3><em>{p.category}</em></div><small>{p.district} · {p.hours}</small><p>{p.description}</p>{p.address&&<div className="place-address">⌖ {p.address}</div>}<div className="place-actions"><Link href="/ask">{tr("AI에게 질문")}</Link>{p.phone&&<a href={`tel:${p.phone}`}>☎ {p.phone}</a>}<a className="primary" href={`https://map.naver.com/p/search/${encodeURIComponent(p.address||p.name)}`} target="_blank" rel="noreferrer">⌁ {tr("길찾기")}</a></div></article>)}</>}
  {page==="my"&&<><div className="my-head"><Header title={tr("마이 라이프")}/><span>{locale.toUpperCase()}</span></div><section className="profile-card"><div><b>{tr(profile.region)} · {tr("체류기간")} {tr(profile.duration)}</b><small>{done.length}/{checklist.length} {tr("완료")} · {tr("저장한 정보")} {saved.length}</small></div><Link href="/">{tr("프로필 수정")}</Link></section><section className="personal-signal"><b>✦ 맞춤 기준</b><span>{profile.duration}</span><span>{profile.purpose||"생활 적응"}</span><span>{profile.hasArc?"등록증 보유":"등록증 미보유"}</span><span>{profile.hasAccount?"계좌 보유":"계좌 미보유"}</span></section><section className="content-section"><h2>{tr("나의 체크리스트")}</h2><p className="section-sub">{tr("한국 생활 시작하기")}</p>{checklist.map(([id,title,category])=>{const matchedGuide=guideForCheck(id,category);return <div className={`check-row ${priorityIds.includes(id)?"priority":""}`} key={id}><button onClick={()=>toggleDone(id)} className={done.includes(id)?"done":""}>{done.includes(id)?"✓":""}</button><b className={done.includes(id)?"strike":""}>{tr(title)}{priorityIds.includes(id)&&<small>우선 추천</small>}</b><Link href={matchedGuide?`/guide/${matchedGuide.id}`:"/guide"}>{tr("자세히 보기")}</Link></div>})}</section><section className="content-section"><h2>{tr("저장한 정보")}</h2>{saved.length===0?<p className="empty">{tr("아직 저장한 정보가 없어요.")}</p>:guideItems.filter(i=>saved.includes(i.id)).map(i=><GuideCard key={i.id} item={i} onOpen={openGuide} tr={tr}/>)}</section><section className="content-section"><h2>{tr("아직 모를 수 있는 것들")}</h2><p className="section-sub">{tr("질문·체크리스트 기록을 바탕으로 골랐어요.")}</p>{rankedGuides.filter(i=>!saved.includes(i.id)).slice(0,3).map(i=><GuideCard key={i.id} item={i} onOpen={openGuide} tr={tr} reason={guideReason(i)}/>)}</section></>}
 </section><nav className="bottom-nav">{nav.map(([id,label,icon])=><Link key={id} className={page===id?"active":""} href={path[id]}><span>{icon}</span>{tr(label)}</Link>)}</nav></main>
}
