"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import MapView,{Place} from "./MapView";
import {categories,checklistByDuration,guideItems,GuideItem} from "./data";
import nearbyPlaces from "../public/nearby_places.json";
import appTranslations from "./app-translations.json";
import {languages,LocaleCode} from "./onboarding-i18n";
type Page="home"|"guide"|"ask"|"nearby"|"my";
type Profile={nickname:string;birthYear:number;region:string;duration:string;language:string;hasArc?:boolean;hasAccount?:boolean;purpose?:string};
type ContactRecommendation={institution:string;department:string;team:string;phone:string;address:string;district:string;type:string};
type ChatAction={label:string;href?:string;checkId?:string;guideId?:string};
type ChatMessage={role:"user"|"assistant";content:string;contact?:ContactRecommendation|null;source?:string;actions?:ChatAction[]};
const nav:[Page,string,string][]=[["home","홈","⌂"],["guide","생활가이드","▤"],["ask","AI에게 질문","?"],["nearby","내 주변","⌖"],["my","마이 라이프","♙"]];
const path:Record<Page,string>={home:"/home",guide:"/guide",ask:"/ask",nearby:"/nearby",my:"/my"};
const allPlaces=nearbyPlaces as Place[];
const placeCategories=["전체",...Array.from(new Set(allPlaces.map(place=>place.category)))];
function useStored<T>(key:string,initial:T){const [v,setV]=useState(initial);useEffect(()=>{const raw=localStorage.getItem(key);if(raw)try{setV(JSON.parse(raw))}catch{}},[key]);const save=(n:T)=>{setV(n);localStorage.setItem(key,JSON.stringify(n))};return [v,save] as const}
function Header({title,sub}:{title:string;sub?:string}){return <header className="page-header"><h1>{title}</h1>{sub&&<p>{sub}</p>}</header>}
function GuideCard({item,onOpen,tr,reason}:{item:GuideItem;onOpen:(i:GuideItem)=>void;tr:(text:string)=>string;reason?:string}){return <button className="guide-card" onClick={()=>onOpen(item)}><span className="guide-icon">{item.icon}</span><span><b>{tr(item.title)}</b><small>{tr(item.desc)}</small><span className="guide-badges"><em>{tr(item.badge)}</em>{reason&&<mark>✦ {tr(reason)}</mark>}</span></span><i>›</i></button>}
export default function MainApp({page}:{page:Page}){
 const [profile]=useStored<Profile>("injoy-profile",{nickname:"유학생",birthYear:2001,region:"연수구",duration:"1개월 미만",language:"한국어"});
 const [saved,setSaved]=useStored<string[]>("injoy-saved",[]),[done,setDone]=useStored<string[]>("injoy-checklist",[]),[extraChecklist,setExtraChecklist]=useStored<[string,string][]>("injoy-extra-checklist",[]),[messages,setMessages]=useStored<ChatMessage[]>("injoy-messages",[]);
 const [filter,setFilter]=useState("전체"),[placeFilter,setPlaceFilter]=useState("전체"),[draft,setDraft]=useState(""),[locale,setLocale]=useState<LocaleCode>("ko");
 useEffect(()=>{const legacy:Record<string,LocaleCode>={"한국어":"ko","English":"en"};const raw=localStorage.getItem("injoy-language")||profile.language||"ko";const next=(legacy[raw]||raw) as LocaleCode;if(languages.some(item=>item.code===next)){setLocale(next);document.documentElement.lang=next}},[profile.language]);
 const dictionary=appTranslations[locale] as Record<string,string>;const tr=(text:string)=>dictionary?.[text]||text;
 const visibleGuides=filter==="전체"?guideItems:guideItems.filter(i=>i.category===filter);const places=placeFilter==="전체"?allPlaces:allPlaces.filter(p=>p.category===placeFilter);const displayPlaces=places.map(p=>({...p,category:tr(p.category),hours:tr(p.hours),description:tr(p.description),district:tr(p.district)}));
 const baseChecklist=checklistByDuration[profile.duration]||checklistByDuration["1개월 미만"];
 const priorityIds=[...(!profile.hasArc?["support"]:[]),...(!profile.hasAccount?["bank","banking"]:[]),...(profile.purpose==="노동자"?["contract","emergency"]:[]),...(profile.purpose==="유학생"?["phone","bank","korean"]:[])];
 const actionChecklist:Record<string,string>={support:"가까운 지원기관 찾아보기",contract:"근로계약서 확인하기",hospital:"병원 이용법 알기",bank:"은행 기본 이해하기",waste:"쓰레기 분리배출 이해하기",phone:"휴대폰 개통하기"};
 const checklist=[...baseChecklist,...extraChecklist.filter(item=>!baseChecklist.some(base=>base[0]===item[0]))].sort((a,b)=>Number(priorityIds.includes(b[0]))-Number(priorityIds.includes(a[0])));
 const latestQuestion=[...messages].reverse().find(message=>message.role==="user")?.content||"";
 const guideReason=(item:GuideItem)=>{if(!profile.hasArc&&item.id==="visa")return "외국인등록증 미보유";if(!profile.hasAccount&&item.id==="bank")return "은행 계좌 미보유";if(profile.purpose==="노동자"&&item.id==="labor")return "근로자 프로필";if(profile.purpose==="유학생"&&["phone","bank"].includes(item.id))return "유학생에게 중요";if(latestQuestion&&[item.title,item.category].some(value=>latestQuestion.includes(value.slice(0,2))))return "최근 질문과 관련";if(!saved.includes(item.id))return `${profile.duration} 맞춤`;return "저장한 관심 정보"};
 // 체크리스트 항목 id가 생활가이드 id와 항상 같지는 않아서(예: "hospital" ↔ "clinic"),
 // id가 정확히 일치하는 가이드가 없으면 같은 카테고리의 가이드로 대신 연결한다.
 const guideForCheck=(id:string,category?:string)=>guideItems.find(g=>g.id===id)||(category?guideItems.find(g=>g.category===category):undefined);
 const rankedGuides=[...guideItems].sort((a,b)=>{const score=(item:GuideItem)=>(!profile.hasArc&&item.id==="visa"?8:0)+(!profile.hasAccount&&item.id==="bank"?7:0)+(profile.purpose==="노동자"&&item.id==="labor"?6:0)+(profile.purpose==="유학생"&&["phone","bank"].includes(item.id)?5:0)+(saved.includes(item.id)?-2:1);return score(b)-score(a)});
 const briefItems=checklist.filter(item=>!done.includes(item[0])).slice(0,3);
 function openGuide(i:GuideItem){location.href=`/guide/${i.id}`}function toggleDone(id:string){setDone(done.includes(id)?done.filter(x=>x!==id):[...done,id])}
 function runAction(action:ChatAction){if(action.checkId&&!checklist.some(item=>item[0]===action.checkId))setExtraChecklist([...extraChecklist,[action.checkId,actionChecklist[action.checkId]||"확인할 정보"]]);if(action.guideId&&!saved.includes(action.guideId))setSaved([...saved,action.guideId]);if(action.href)location.href=action.href}
 // 실제로 주제가 매칭됐거나(기관 후보를 받았거나) 카테고리 키워드가 잡혔을 때만 "다음 행동" 버튼을 붙인다.
 // 매칭이 하나도 없으면(=잡담/인사 등 실질 정보가 없는 응답) 빈 배열을 반환해 엉뚱한 체크리스트/가이드 버튼이 안 붙게 한다.
 function actionsFor(q:string,contact?:ContactRecommendation|null):ChatAction[]{const lower=q.toLowerCase();let guideId="visa",checkId="support",matched=false;if(/임금|노동|근로|해고/.test(lower)){guideId="labor";checkId="contract";matched=true}else if(/병원|의료|아파|진료/.test(lower)){guideId="clinic";checkId="hospital";matched=true}else if(/은행|계좌/.test(lower)){guideId="bank";checkId="bank";matched=true}else if(/쓰레기|재활용/.test(lower)){guideId="waste";checkId="waste";matched=true}else if(/휴대폰|통신|유심/.test(lower)){guideId="phone";checkId="phone";matched=true}if(!matched&&!contact)return [];const alreadyListed=checklist.some(item=>item[0]===checkId);return [{label:alreadyListed?"체크리스트에서 확인":"체크리스트에 추가",checkId:alreadyListed?undefined:checkId,href:alreadyListed?"/my":undefined},{label:"관련 가이드 저장",guideId},{label:contact?"가까운 기관 확인":"내 주변 확인",href:"/nearby"}]}
 async function ask(e:FormEvent){e.preventDefault();const q=draft.trim();if(!q)return;const history=messages.slice(-10).map(m=>({role:m.role,content:m.content}));const next:ChatMessage[]=[...messages,{role:"user",content:q}];setMessages(next);setDraft("");try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,history,profile:{...profile,locale,language:languages.find(item=>item.code===locale)?.name||locale}})});const data=await res.json();const actions=data.source==="기본 대화"?undefined:actionsFor(q,data.contact);setMessages([...next,{role:"assistant",content:data.answer||tr("답변을 준비하지 못했어요."),contact:data.contact,source:data.source,actions}])}catch{setMessages([...next,{role:"assistant",content:tr("연결이 원활하지 않아요. 생활가이드에서 관련 정보를 먼저 확인해주세요."),actions:actionsFor(q)}])}}
 return <main className="app-shell"><div className="app-speaker"/><header className="app-topbar"><span className="app-brand"><i>INJOY</i><b>INCHEON</b></span><span className="locale-pill">{languages.find(item=>item.code===locale)?.flag} {locale.toUpperCase()}</span></header><section className="app-content">
  {page==="home"&&<><section className="hero"><span>INJOY · LIFE NAVIGATOR</span><h1>{profile.nickname},<br/>{tr("인천 생활을 함께할게요")}</h1><p>{tr(profile.region)} · {tr("체류기간")} {tr(profile.duration)}</p><div>{tr("오늘 필요한 정보만 쉽고 빠르게 확인하세요.")}</div></section><section className="personal-brief"><header><div><small>✦ PERSONAL BRIEFING</small><h2>{tr("오늘의 맞춤 브리핑")}</h2></div><span>{briefItems.length}{tr("개 추천")}</span></header><p>{tr(profile.region)} · {tr(profile.purpose||"생활 적응")} · {tr(profile.duration)} {tr("프로필을 반영했어요.")}</p><div>{briefItems.map(([id,title])=><button key={id} onClick={()=>toggleDone(id)}><i>{done.includes(id)?"✓":""}</i><span><b>{tr(title)}</b><small>{tr(priorityIds.includes(id)?"프로필 조건에 따라 우선 추천":"아직 완료하지 않은 항목")}</small></span><em>›</em></button>)}</div><Link href="/my">{tr("전체 맞춤 체크리스트 보기")} →</Link></section><section className="content-section"><h2>{tr("생활가이드")}</h2><div className="category-grid">{[["🚌","교통"],["🏥","의료"],["💳","은행·금융"],["🏠","주거"],["📱","통신"],["♻️","일상생활"],["💼","직장·노동"],["🏛️","행정·비자"],["🚨","긴급상황"]].map(x=><Link href={`/guide?category=${encodeURIComponent(x[1])}`} key={x[1]}><span>{x[0]}</span>{tr(x[1])}</Link>)}</div></section><section className="content-section"><h2>{tr("당신을 위한 추천")}</h2><p className="section-sub">{tr("프로필과 완료 기록을 바탕으로 골랐어요.")}</p>{rankedGuides.slice(0,3).map(i=><GuideCard key={i.id} item={i} onOpen={openGuide} tr={tr} reason={guideReason(i)}/>)}</section></>}
  {page==="guide"&&<><Header title={tr("생활가이드")} sub={tr("긴 문서가 아니라, 실행 가능한 단계로 정리했어요.")}/><div className="chip-row">{categories.map(c=><button className={filter===c?"active":""} onClick={()=>setFilter(c)} key={c}>{tr(c)}</button>)}</div>{visibleGuides.map(i=><GuideCard key={i.id} item={i} onOpen={openGuide} tr={tr}/>)}</>}
  {page==="ask"&&<><Header title={tr("AI에게 질문")} sub={tr("한국 생활에서 막히는 걸 편하게 물어보세요.")}/>{messages.length===0&&<section className="chat-hero"><b>✦ LIFE NAVIGATOR</b><h2>{profile.nickname}, {tr("무엇이 궁금하세요?")}</h2><p>{tr("행정·의료·은행·통신처럼 처음엔 놓치기 쉬운 정보도 함께 안내해요.")}</p></section>}<div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.role==="assistant"&&<b>✦ {tr("AI 답변")}</b>}<p>{m.content}</p>{m.contact&&<section className="contact-card"><small>{tr(m.contact.district)} · {tr("기준 추천 기관")}</small><strong>{m.contact.institution}</strong><span>{m.contact.department}{m.contact.team&&` · ${m.contact.team}`}</span>{m.contact.address&&<address>{m.contact.address}</address>}<div><a href={`tel:${m.contact.phone.replace(/\s/g,"")}`}>☎ {m.contact.phone}</a><a href={`https://map.naver.com/p/search/${encodeURIComponent(m.contact.address||m.contact.institution)}`} target="_blank" rel="noreferrer">{tr("지도에서 보기")} →</a></div></section>}{!!m.actions?.length&&<div className="next-actions"><small>{tr("다음 행동을 바로 실행해보세요")}</small>{m.actions.map(action=><button key={action.label} onClick={()=>runAction(action)}>＋ {tr(action.label)}</button>)}</div>}</div>)}</div><div className="suggestions">{["외국인등록증은 언제 신청해야 하나요?","쓰레기 배출은 어디에 문의하나요?","가까운 내과 전화번호를 알려주세요"].map(q=><button key={q} onClick={()=>setDraft(q)}>{tr(q)}</button>)}</div><form className="chat-form" onSubmit={ask}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder={tr("무엇이든 물어보세요...")}/><button>↑</button></form></>}
  {page==="nearby"&&<><Header title={tr("내 주변")} sub={tr("실제로 도움을 받을 수 있는 곳들.")}/><MapView places={displayPlaces}/><div className="chip-row">{placeCategories.map(c=><button className={placeFilter===c?"active":""} onClick={()=>setPlaceFilter(c)} key={c}>{tr(c)}</button>)}</div>{displayPlaces.map(p=><article className="place-card" key={p.id}><div><h3>{p.name}</h3><em>{p.category}</em></div><small>{p.district} · {p.hours}</small><p>{p.description}</p>{p.address&&<div className="place-address">⌖ {p.address}</div>}<div className="place-actions"><Link href="/ask">{tr("AI에게 질문")}</Link>{p.phone&&<a href={`tel:${p.phone}`}>☎ {p.phone}</a>}<a className="primary" href={`https://map.naver.com/p/search/${encodeURIComponent(p.address||p.name)}`} target="_blank" rel="noreferrer">⌁ {tr("길찾기")}</a></div></article>)}</>}
  {page==="my"&&<><div className="my-head"><Header title={tr("마이 라이프")}/><span>{locale.toUpperCase()}</span></div><section className="profile-card"><div><b>{tr(profile.region)} · {tr("체류기간")} {tr(profile.duration)}</b><small>{done.length}/{checklist.length} {tr("완료")} · {tr("저장한 정보")} {saved.length}</small></div><Link href="/">{tr("프로필 수정")}</Link></section><section className="personal-signal"><b>✦ 맞춤 기준</b><span>{profile.duration}</span><span>{profile.purpose||"생활 적응"}</span><span>{profile.hasArc?"등록증 보유":"등록증 미보유"}</span><span>{profile.hasAccount?"계좌 보유":"계좌 미보유"}</span></section><section className="content-section"><h2>{tr("나의 체크리스트")}</h2><p className="section-sub">{tr("한국 생활 시작하기")}</p>{checklist.map(([id,title,category])=>{const matchedGuide=guideForCheck(id,category);return <div className={`check-row ${priorityIds.includes(id)?"priority":""}`} key={id}><button onClick={()=>toggleDone(id)} className={done.includes(id)?"done":""}>{done.includes(id)?"✓":""}</button><b className={done.includes(id)?"strike":""}>{tr(title)}{priorityIds.includes(id)&&<small>우선 추천</small>}</b><Link href={matchedGuide?`/guide/${matchedGuide.id}`:"/guide"}>{tr("자세히 보기")}</Link></div>})}</section><section className="content-section"><h2>{tr("저장한 정보")}</h2>{saved.length===0?<p className="empty">{tr("아직 저장한 정보가 없어요.")}</p>:guideItems.filter(i=>saved.includes(i.id)).map(i=><GuideCard key={i.id} item={i} onOpen={openGuide} tr={tr}/>)}</section><section className="content-section"><h2>{tr("아직 모를 수 있는 것들")}</h2><p className="section-sub">{tr("질문·체크리스트 기록을 바탕으로 골랐어요.")}</p>{rankedGuides.filter(i=>!saved.includes(i.id)).slice(0,3).map(i=><GuideCard key={i.id} item={i} onOpen={openGuide} tr={tr} reason={guideReason(i)}/>)}</section></>}
 </section><nav className="bottom-nav">{nav.map(([id,label,icon])=><Link key={id} className={page===id?"active":""} href={path[id]}><span>{icon}</span>{tr(label)}</Link>)}</nav></main>
}
